[build]
builder = "nixpacks"

[phases.setup]
commands = ["pip install --upgrade pip"]

[phases.install]
commands = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend.wsgi --bind 0.0.0.0:$PORT"
